services:
  vllm:
    image: test-vllm-rtx4060:v1.0.0
    container_name: vllm-gpu

    ports:
      - "8000:8000"

    volumes:
      - ../models:/workspace/models
      - ../hf-cache:/root/.cache/huggingface
      - ../code_base:/workspace/code_base

    environment:
      HF_HOME: /root/.cache/huggingface
      TRANSFORMERS_CACHE: /root/.cache/huggingface
      HF_HUB_ENABLE_HF_TRANSFER: "1"
      VLLM_WORKER_MULTIPROC_METHOD: spawn

      # GPU visibility
      CUDA_VISIBLE_DEVICES: "0"
      NVIDIA_VISIBLE_DEVICES: "0"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"

      # debug için faydalı
      VLLM_LOGGING_LEVEL: "DEBUG"

    # NVIDIA GPU
    runtime: nvidia

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    shm_size: "8gb"
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]